"""Deeper, section-specific lesson notes displayed before each question set."""

DEEP_NOTES = {
    # Domain 1 — Security and Risk Management
    "1.1": [
        "Competence includes recognising the limits of your expertise. For an unfamiliar assignment, disclose limitations, obtain qualified help and agree a realistic scope; accepting work without the ability to perform it can harm the principal.",
        "Conflicts may involve financial interests, gifts, outside employment or competing clients. Disclose them before making decisions, recuse yourself when necessary, and document the agreed resolution while protecting confidential information.",
        "The ethics canons form a priority hierarchy. Protection of society, the common good, public trust, and necessary infrastructure comes before duties to a client, employer, colleague, or the profession.",
        "A professional should gather facts, preserve confidentiality, avoid conflicts of interest, and escalate through appropriate channels. An instruction from a principal does not excuse illegal or unethical conduct.",
        "Certification holders are expected to protect the value of the credential: represent qualifications honestly, avoid conduct that discredits the profession, and support competent professional development.",
    ],
    "1.2": [
        "An asset is something of value; a threat is a potential cause of harm; a vulnerability is a weakness; an exploit uses a weakness; risk combines the likelihood and consequences of harm. A threat without a relevant vulnerability may not create the same exposure.",
        "An availability problem can become an integrity problem: a failed transaction may leave inconsistent records. Design controls around business outcomes, including accuracy, timeliness and recoverability, rather than assigning each control to only one CIA category.",
        "Security objectives interact. Encryption mainly supports confidentiality; hashes and message authentication codes support integrity; redundancy, fault tolerance, and recovery planning support availability. A control may support more than one objective.",
        "Identification is the claim of an identity. Authentication verifies the claim, authorization grants permitted actions, and accounting or auditing records what occurred. Together these support accountability.",
        "Privacy is concerned with appropriate collection, use, disclosure, retention, and disposal of personal information. It overlaps confidentiality but is governed by purpose, consent, and individual rights as well as secrecy.",
        "Controls can be described by implementation type and by function. For example, a fence is physical and preventive, a log review is administrative or operational and detective, and restoring a backup is corrective or recovery-oriented.",
    ],
    "1.3": [
        "Risk appetite describes the amount and type of risk the organisation is willing to pursue; tolerance sets acceptable variation around objectives. Escalate exposures exceeding delegated limits to the appropriate owner or governing body.",
        "In mergers and acquisitions, security due diligence examines inherited systems, identities, data, contracts, liabilities and incidents. Integration requires explicit ownership and access changes; divestiture requires separating trust relationships and retaining or transferring data lawfully.",
        "For a customer database, the business owner approves classification and access needs; the custodian configures protection; the CISO advises on risk; the auditor checks evidence independently. Approval, operation and assurance are distinct responsibilities.",
        "The board and senior leadership remain accountable for organizational risk. A data owner determines classification and access requirements; a custodian operates safeguards; users follow requirements; independent assurance evaluates effectiveness.",
        "A security program should trace objectives to business goals, legal duties, and measurable outcomes. Useful metrics show trends, control performance, exposure, and decisions needed rather than merely counting activity.",
        "Frameworks serve different purposes: governance and control objectives, risk management, control catalogs, service management, and certifiable management systems should not be treated as interchangeable.",
    ],
    "1.4": [
        "Intellectual property protects different things: copyright covers original expression, patents cover qualifying inventions, trademarks identify commercial origin, and trade secrets depend on maintaining secrecy. A licence grants specified rights without necessarily transferring ownership.",
        "A data controller determines purposes and means of processing; a processor acts on its behalf under agreed instructions. Outsourcing processing creates oversight and contractual duties; the precise legal roles and rights depend on the applicable privacy regime.",
        "Jurisdiction determines which law applies. Organizations must consider where data subjects, systems, processing, and providers are located, as well as contractual and sector-specific obligations.",
        "Due diligence is the continuing process of understanding risk; due care is the reasonable action taken in response. Documentation helps demonstrate that decisions were informed, proportionate, approved, and monitored.",
        "Privacy programs apply data minimization, purpose limitation, transparency, accuracy, retention limits, safeguards, and accountable handling of data-subject requests and breaches.",
        "Legal holds suspend normal destruction when litigation is anticipated. Evidence should be relevant, authentic, reliable, complete, and handled under a documented chain of custody.",
        "Contracts should allocate security responsibilities, notification duties, audit rights, data ownership, permitted processing, subcontractor controls, return or destruction, and liability.",
    ],
    "1.5": [
        "Investigative authority and standard of proof are separate questions. Permission to access company systems does not automatically permit searching personal devices or disclosing records externally; establish scope and consult the appropriate legal authority.",
        "Preserve relevant material when a dispute is foreseeable. Ordinary log rotation, mailbox deletion or device reimaging may destroy evidence, so coordinate holds with records owners and retain a documented history of collection and access.",
        "The investigation type determines authority, procedure, privacy expectations, evidence standards, and possible consequences. Internal investigators must still follow policy, employment law, and authorized monitoring boundaries.",
        "Criminal matters prioritize lawful collection and preservation for prosecution; civil matters support disputes between parties; regulatory matters demonstrate compliance; administrative matters enforce organizational rules.",
        "Coordinate early with legal counsel, human resources, management, and law enforcement as appropriate. Premature action can contaminate evidence, exceed authority, or alert a suspect.",
    ],
    "1.6": [
        "A policy lifecycle includes identifying a need, consulting stakeholders, drafting, legal and operational review, approval, publication, acknowledgement, enforcement and scheduled review. Obsolete versions should be withdrawn so staff follow one authoritative version.",
        "A baseline is the starting configuration, while tailoring adjusts it to the system's context. Record why a control is added, strengthened or replaced; an undocumented deviation is different from an approved exception.",
        "Example: policy requires protected remote access; a standard mandates MFA; a baseline disables unused VPN features; a procedure explains enrollment; a guideline recommends secure working practices. Each document answers a different operational question.",
        "Documents need an owner, approval authority, version control, review cycle, exception process, and communication plan. An unpublished or unenforced policy provides little practical protection.",
        "Exceptions should identify the requirement, business justification, affected assets, risk owner, compensating controls, approval, expiration date, and periodic review.",
        "Policies should be technology-neutral enough to remain stable, while standards and procedures may change as technology, threats, or business processes change.",
    ],
    "1.7": [
        "A BIA studies the consequences of disruption; a risk assessment studies causes, likelihood and impact. Combine them to choose recovery priorities and scenarios, but do not let a low estimated probability obscure an intolerable business impact.",
        "Recovery time includes detection, decision, mobilisation, restoration and validation. Work recovery time covers reconciling backlogs and returning business processing to an acceptable state; a technically running server alone does not prove business recovery.",
        "A BIA begins with products and services, then maps the processes, people, facilities, technology, information, suppliers, and dependencies needed to deliver them.",
        "Impact normally grows over time and may be financial, operational, legal, safety-related, or reputational. Criticality is based on business impact, not on how technically important a system appears.",
        "Example: RTO = 4 hours means restore service within four hours; RPO = 15 minutes means lose no more than fifteen minutes of data. If MTD = 8 hours, recovery and subsequent business catch-up must fit within that limit.",
        "Priorities and dependencies matter: a high-priority application cannot recover if identity, networking, facilities, staff, or a key supplier remains unavailable.",
    ],
    "1.8": [
        "Screening should be proportionate to the role and permitted by local law. Personnel records themselves are sensitive: restrict access, retain only what is needed, and protect information obtained through background checks.",
        "For a departing employee, coordinate HR, management, IT and physical security around the effective separation time. Disable authentication, revoke active sessions, recover equipment and transfer business records without exposing unnecessary personal information.",
        "Personnel controls follow the entire lifecycle: define roles, screen proportionately, establish agreements, provision least privilege, train, monitor role changes, and remove access and assets promptly at separation.",
        "Separation of duties prevents one person from completing a sensitive transaction alone. Job rotation and mandatory vacation increase the chance that concealed errors or fraud will be discovered.",
        "Transfers require the same discipline as termination: remove old privileges before or as new privileges are granted, review conflicts, and update physical and logical access.",
        "Third parties and contractors need named sponsors, time-bounded access, contractual confidentiality, appropriate screening, monitoring, and confirmed offboarding.",
    ],
    "1.9": [
        "The risk register connects each scenario to an asset, cause, consequence, likelihood, impact, controls, owner, treatment and review date. A risk assessment describes exposure; a treatment plan assigns actions and resources to change it.",
        "Control cost includes purchase, integration, staffing, training, maintenance, performance impact and disposal. Evaluate uncertainty and multiple scenarios rather than treating an estimated ALE as a precise prediction of next year's loss.",
        "Risk analysis starts with scope and context, then identifies assets, threats, vulnerabilities, existing controls, likelihood, and impact. Results are recorded in a risk register with owners and treatment decisions.",
        "Inherent risk exists before controls; residual risk remains after controls; control risk is the chance that a safeguard fails or is inadequate. Only an authorized business risk owner can accept residual risk.",
        "Example: an asset worth R200,000 with 25% exposure has SLE = R50,000. At 0.2 incidents per year, ALE = R10,000. A control reducing ALE to R3,000 saves R7,000 annually before its costs; estimates still depend on uncertain inputs.",
        "Treatment changes likelihood or impact through mitigation, avoids the activity, transfers or shares consequences, or accepts the exposure. Transferring financial loss does not transfer accountability.",
        "Risk management is continuous: monitor indicators, control performance, environmental change, exceptions, incidents, and treatment deadlines, then reassess when assumptions change.",
    ],
    "1.10": [
        "A data-flow diagram shows processes, stores, external actors and movement of data. Mark trust boundaries where assumptions change, then examine authentication, authorisation, validation and logging at each crossing.",
        "Example: a payment API may face spoofed users, altered amounts, disputed transactions, exposed account details, resource exhaustion and privilege escalation. These map to STRIDE and lead to distinct controls rather than one generic recommendation to encrypt.",
        "Threat modeling is most valuable early, when trust boundaries and design choices can still change cheaply. Define the system, assets, data flows, actors, entry points, and assumptions before enumerating threats.",
        "STRIDE categorizes what can go wrong; attack trees show paths to an attacker goal; misuse or abuse cases describe hostile behavior; risk scoring helps prioritize treatment.",
        "A useful model connects each threat to affected assets, preconditions, existing controls, likelihood, impact, recommended mitigation, and an accountable owner. It must be updated as architecture changes.",
    ],
    "1.11": [
        "An SBOM inventories software components; it does not prove that components are secure. Combine it with version tracking, vulnerability analysis, build provenance, maintenance commitments and checks that a vulnerable component is actually reachable.",
        "Concentration risk arises when supposedly independent suppliers depend on the same cloud, telecom provider or region. Exit planning should prove that data, keys, configurations and operational knowledge can be transferred to an alternative.",
        "Supply-chain risk exists throughout selection, contracting, development, delivery, operation, support, and disposal. Map critical suppliers and their dependencies rather than assessing only the direct vendor.",
        "Assurance may include security questionnaires, independent reports, architecture evidence, vulnerability disclosure practices, software bills of materials, provenance, secure update mechanisms, and on-site review.",
        "Contracts should state minimum controls, incident and vulnerability notification times, audit and testing rights, data location and return, subcontractor requirements, service continuity, support lifetime, and exit assistance.",
        "Continuously monitor material changes, concentration risk, breaches, financial health, unsupported components, and fourth-party dependencies. Initial due diligence is not sufficient.",
    ],
    "1.12": [
        "Social engineering uses urgency, authority, familiarity, fear or reward to bypass normal judgment. Teach a repeatable response: pause, verify through a known channel, follow the approval process and report suspicious activity.",
        "A rise in reported phishing may indicate better awareness rather than more failures. Interpret reporting, click rates, credential submission and time to report together, with consistent definitions and a culture that encourages early disclosure.",
        "Build training from role and risk analysis. Everyone needs core awareness; administrators, developers, executives, investigators, and privileged users need content tied to their responsibilities.",
        "Use multiple interventions: onboarding, periodic refreshers, event-driven updates, simulations, job aids, and targeted coaching. Training should occur before access and after significant role or threat changes.",
        "Measure behavior and outcomes, not attendance alone. Useful evidence includes reporting rates, simulation trends, repeat failures, incident patterns, assessment results, and remediation completion.",
        "Content must be accessible, culturally appropriate, current, and reinforced by managers and policy. Lessons from incidents and testing should feed the next training cycle.",
    ],

    # Domain 2 — Asset Security
    "2.1": [
        "Sensitivity measures harm from disclosure; criticality measures dependence on an asset's availability and correct operation. A public emergency website can have low confidentiality needs but very high integrity and availability requirements.",
        "Aggregation can raise classification: individual employee details may appear harmless, while a combined dataset exposes payroll or identity patterns. Classification decisions should consider the complete dataset, its context and likely combinations.",
        "Classification expresses business sensitivity and criticality so handling and controls can be applied consistently. The owner classifies; custodians implement; users handle the asset according to its label.",
        "Consider confidentiality, integrity, availability, privacy, legal requirements, replacement cost, operational dependency, and harm from disclosure or alteration. Labels should be few, clearly defined, and usable.",
        "An inventory records ownership, location, classification, lifecycle state, dependencies, and retention. Discovery and reconciliation are needed because unmanaged assets cannot be protected reliably.",
        "Classification may change as information ages, is aggregated, becomes public, or is subject to a new obligation. Owners should review and formally declassify or relabel it.",
    ],
    "2.2": [
        "Data in transit needs protected channels and verified recipients; data at rest needs controlled storage and key protection; data in use needs process isolation and access enforcement. Disk encryption does not prevent an authorised running process from reading plaintext.",
        "Removable media controls include approved devices, encryption, malware checks, custody records and restrictions on copying. A printed label communicates handling requirements; it does not technically enforce them.",
        "Handling rules translate classification into requirements for collection, labeling, access, copying, storage, transmission, transport, sharing, backup, retention, and destruction.",
        "Protection should follow the asset across formats and locations. Printing, removable media, screenshots, exports, test copies, and backups can bypass controls applied to the primary system.",
        "Use authorized channels and verify recipient, destination, encryption, packaging, custody, and receipt when transferring sensitive assets. Record exceptions and incidents.",
    ],
    "2.3": [
        "Resource ownership and resource custody may differ. A department may own the business risk while an IT team operates a cloud service; both roles need named contacts, approved configurations, support arrangements and decommissioning criteria.",
        "Provision only the resources needed for the approved purpose. Excess accounts, services, open ports, storage and network permissions increase exposure; templates should start with restrictive settings and enable features through approved change.",
        "Secure provisioning creates a controlled asset from an approved request. Verify business need and ownership, acquire from trusted sources, record inventory, apply a hardened baseline, patch, configure logging, label, and test before release.",
        "Credentials, keys, certificates, service accounts, and licenses must be generated or assigned securely and linked to accountable owners. Default or shared credentials should not survive provisioning.",
        "Cloud and automated infrastructure need approved templates, policy checks, secrets management, tagging, and drift detection so rapid deployment does not bypass governance.",
        "Deprovisioning is part of provisioning: define how the resource, access, data, keys, records, and dependencies will be retired when the need ends.",
    ],
    "2.4": [
        "Masking conceals selected values for display or testing; tokenisation replaces a value with a substitute linked through a protected mapping. Pseudonymised information may still identify a person when combined with additional data; it is not automatically anonymous.",
        "Backups, caches, search indexes, exports and replicas extend the lifecycle beyond the main database. Map these copies so retention, access changes, legal holds and destruction requests are applied to the correct locations.",
        "The data lifecycle covers creation or collection, use, storage, sharing, archival, and destruction. Security and privacy requirements must travel with data through every stage and every copy.",
        "Data location and flow mapping reveal processors, interfaces, trust boundaries, jurisdictions, shadow copies, and concentration points. This supports classification, privacy analysis, DLP, and incident response.",
        "Deletion removes a file reference; sanitisation addresses recoverable data. Cryptographic erase works only if the target data was properly encrypted and all relevant key copies are sanitised. Check the result and record the media, method, operator and disposition.",
        "At end of life, validate retention authority, release legal holds, destroy all governed copies where feasible, and retain evidence of disposal.",
    ],
    "2.5": [
        "The retention clock may start at account closure, contract expiry, transaction date or another defined event. A schedule without that trigger can produce inconsistent deletion even when everyone uses the same stated retention period.",
        "An archive preserves records for long-term retrieval; a backup restores a system after loss. Archived records need searchable metadata and durable formats, while backup rotation is designed around restoration and may not meet records-management needs.",
        "Retention schedules reconcile legal, regulatory, contractual, operational, historical, and litigation needs. Keeping data too briefly creates compliance and business risk; keeping it too long increases exposure and discovery cost.",
        "Schedules identify record category, owner, event that starts the clock, retention period, storage and protection requirements, disposition method, and exceptions such as legal holds.",
        "Apply the schedule consistently to active systems, archives, backups, collaboration platforms, endpoints, and provider-held copies. Destruction should be authorized, repeatable, and auditable.",
    ],
    "2.6": [
        "DLP can inspect content, labels and context at endpoints, networks or cloud services. It may warn, block, quarantine or record a transfer, but encrypted traffic, unmanaged devices and false positives can limit coverage.",
        "Scoping selects which systems and requirements apply; tailoring adjusts controls to the context. Document control inheritance from a provider and the controls still operated by the customer, especially identities, data handling and configuration.",
        "Select controls from classification, risk, usage, location, technology, and obligations. A control set may combine access control, encryption, tokenization, masking, DLP, logging, backup, and physical protection.",
        "Map each requirement to an implemented control and evidence source. Compliance is demonstrated through configuration records, logs, tests, reviews, approvals, and remediation—not by policy statements alone.",
        "Compensating controls must address the original objective to a comparable level, be approved by the risk owner, documented, monitored, and revisited until the primary requirement can be met.",
    ],

    # Domain 3 — Security Architecture and Engineering
    "3.1": [
        "Complete mediation checks every access through a trusted mechanism; open design means security does not depend on hiding the design. Economy of mechanism reduces complexity, while psychological acceptability makes secure behaviour practical for users.",
        "Fail-secure protects access restrictions during failure; fail-safe protects people or the surrounding process. A door may need to permit emergency exit while denying entry, so specify failure behaviour for each direction and hazard.",
        "Secure design begins with requirements and threat assumptions. Defense in depth, least privilege, separation of duties, secure defaults, complete mediation, fail-safe behavior, simplicity, and minimized attack surface reinforce one another.",
        "Trust must be explicit and limited. Identify trust boundaries, validate every crossing, isolate components, reduce shared dependencies, and avoid relying on secrecy of design as the primary safeguard.",
        "Resilience assumes components will fail or be compromised. Use redundancy without common-mode failure, graceful degradation, fault isolation, recovery capability, monitoring, and tested operational procedures.",
        "Architecture decisions should be traceable to business and security requirements, reviewed independently, and reassessed when threats, dependencies, or system context change.",
    ],
    "3.2": [
        "A lattice arranges security labels in a partial order, often combining levels and compartments. A higher clearance alone does not grant access to every compartment: the subject must satisfy both label dominance and need to know.",
        "Take-Grant models how rights can propagate; Graham-Denning describes controlled operations for creating and deleting subjects, objects and rights. Noninterference asks whether activity in one security domain can affect observations in another.",
        "A security model is a formal way to express permitted information flow or access. A model's objective matters: confidentiality models prevent improper disclosure, while integrity models prevent improper modification.",
        "A Secret-cleared subject cannot read Top Secret or write Secret data to an Unclassified object under Bell-LaPadula. Under strict Biba, a high-integrity process cannot read low-integrity input, and a low-integrity process cannot write high-integrity records.",
        "Clark-Wilson protects commercial integrity through well-formed transactions, constrained data items, transformation procedures, integrity verification, separation of duties, and auditing.",
        "Brewer-Nash prevents conflicts of interest by changing access rights according to previously accessed company data. Information-flow and noninterference models examine whether actions leak information across boundaries.",
        "State-machine reasoning asks whether every transition preserves a secure state. Access matrices, capability lists, and ACLs describe subjects, objects, and allowable operations from different viewpoints.",
    ],
    "3.3": [
        "Control design asks whether the safeguard could address the requirement; implementation asks whether it was deployed correctly; operating effectiveness asks whether it consistently works. A well-written standard does not prove that systems comply.",
        "Common controls serve multiple systems, system-specific controls belong to one system, and hybrid controls divide responsibility. Identify who supplies evidence and who fixes a failure when a system inherits shared protection.",
        "Translate requirements into control objectives before choosing products. Consider threat, risk, architecture, data classification, assurance, usability, interoperability, cost, and operational capability.",
        "Preventive controls reduce likelihood, detective controls reveal events, corrective controls limit or repair damage, recovery controls restore service, and compensating controls provide alternate protection.",
        "Evaluate effectiveness in context: placement, configuration, dependencies, bypass paths, failure mode, monitoring, ownership, maintenance, and evidence all determine whether a control actually works.",
        "A balanced architecture uses administrative, technical, and physical controls. Overreliance on one layer creates single points of control failure.",
    ],
    "3.4": [
        "Virtual memory maps a process's addresses to physical memory and separates address spaces. Swapping can leave sensitive material on disk; memory reuse must prevent one process from reading another's residual contents.",
        "A covert storage channel encodes information in shared state, such as a file attribute; a covert timing channel encodes it in delays or resource use. These channels bypass intended communication rules and may persist despite ordinary file permissions.",
        "A trusted computing base contains the mechanisms that enforce security policy. Its security kernel should mediate every access, resist tampering, and be small enough to analyze and test.",
        "Protection rings and processor modes separate privileged kernel operations from user processes. Memory protection, process isolation, virtualization boundaries, secure boot, and hardware roots of trust extend that separation.",
        "Firmware and embedded systems are difficult to patch and often highly trusted. Require signed updates, protected keys, minimal services, inventory, support commitments, and safe failure behavior.",
        "Virtualization and cloud introduce shared physical resources and management planes. Protect the hypervisor, images, orchestration interfaces, snapshots, metadata services, and tenant boundaries.",
        "Evaluation vocabulary: the Target of Evaluation is the evaluated product; its Security Target states its claims; a Protection Profile describes reusable requirements for a product class. Assurance measures confidence in evaluated claims, not immunity to attack.",
    ],
    "3.5": [
        "In IaaS the customer generally manages guest operating systems and applications; in PaaS the provider manages more of the runtime; in SaaS it manages the application service. Data, identity, configuration and contractual responsibilities still require explicit allocation.",
        "Containers share the host kernel, while virtual machines have separate guest operating systems. Neither provides absolute isolation: exposed management interfaces, excessive privileges, mounted host resources and untrusted images can undermine the boundary.",
        "Assess complete solutions, not isolated components. Interfaces, inherited trust, management planes, default settings, unsupported dependencies, and integration shortcuts commonly create the most serious weaknesses.",
        "Client systems face malicious content, credential theft, local privilege escalation, and data loss. Server systems add exposed services, application and database flaws, administrative interfaces, and availability concerns.",
        "Industrial, embedded, and cyber-physical systems prioritize safety and availability and may have long lifecycles. Segmentation, allowlisting, passive monitoring, controlled maintenance, and compensating controls may be safer than immediate change.",
        "Distributed, edge, mobile, IoT, and microservice designs multiply identities, APIs, data flows, and update paths. Inventory, secure onboarding, strong device identity, signed updates, and centralized visibility are essential.",
    ],
    "3.6": [
        "AES uses 128-bit blocks and supports 128-, 192- and 256-bit keys; block size and key length describe different properties. A longer key does not correct a broken mode, weak random generator or exposed plaintext.",
        "Certificate validation checks the trust chain, intended identity, validity period, permitted usage and revocation status where required. A certificate for the wrong hostname remains unsuitable even if a trusted CA signed it.",
        "Forward secrecy limits exposure of past sessions if a long-term key is later compromised, usually through ephemeral key agreement. It does not protect plaintext already stolen from an endpoint or a live session whose session keys are exposed.",
        "Choose cryptography from the required service: confidentiality, integrity, origin authentication, or non-repudiation. Algorithm, key length, mode, protocol, implementation, and key management all affect the result.",
        "Symmetric cryptography is fast and suited to bulk data but requires a shared secret. Asymmetric cryptography enables key agreement and signatures but is slower; hybrid systems use it to establish symmetric session keys.",
        "For a signed download, verify the publisher's public key and then the signature. An attacker who replaces both a file and its plain hash defeats that hash comparison; they cannot create a valid signature without the signing key.",
        "PKI binds public keys to identities through certificates. Registration validates identity, certification issues and signs, repositories publish, and revocation status is checked using CRLs or OCSP.",
        "Key management covers generation, distribution, storage, rotation, backup or escrow where appropriate, recovery, revocation, archival, and destruction. Weak key handling defeats strong algorithms.",
        "Key handling matters in modes: ECB reveals repeated blocks; CBC encryption needs separate authentication; CTR and GCM must avoid nonce reuse with the same key. For AES-GCM, verify the authentication tag before accepting plaintext.",
    ],
    "3.7": [
        "Preimage resistance makes it difficult to recover an input from its hash; second-preimage resistance makes it difficult to find another input matching a given input's hash; collision resistance makes it difficult to find any matching pair.",
        "A salt gives each password hash a distinct input and defeats reuse of precomputed tables across accounts. A deliberately expensive password-hashing function slows guesses; salting alone does not make fast general-purpose hashing suitable for password storage.",
        "Cryptanalysis targets mathematics, keys, implementations, protocols, or human behavior. Brute force searches key space; frequency and known-plaintext methods exploit patterns; differential and linear methods analyze cipher behavior.",
        "Side-channel attacks infer secrets from timing, power, electromagnetic leakage, cache behavior, or faults rather than breaking the algorithm directly. Constant-time operations and physical protections reduce leakage.",
        "Birthday attacks exploit collision probability in hashes; meet-in-the-middle attacks reduce the benefit of multiple encryption stages; padding oracles expose information through error behavior.",
        "Assess practical security, including entropy, random-number generation, protocol negotiation, implementation defects, downgrade resistance, and key protection.",
    ],
    "3.8": [
        "CPTED uses natural surveillance, controlled paths and visible territorial boundaries to discourage unwanted activity. Clear sightlines, purposeful landscaping and separated public entrances can improve security without turning every area into a restricted zone.",
        "A distant recovery site can still share a flood basin, electricity supplier or network carrier with the primary. Assess correlated hazards and practical staff access when deciding whether geographic separation provides real resilience.",
        "Site selection considers natural hazards, crime, political conditions, utilities, transportation, emergency response, neighboring risks, jurisdiction, and geographic concentration of critical dependencies.",
        "Layer protection from the property boundary to the building, controlled interior, restricted areas, equipment, and media. Each layer should deter, delay, detect, assess, and support response.",
        "Separate public, delivery, office, operations, and high-security zones. Route people, materials, utilities, and communications so one pathway cannot bypass controls.",
        "Resilient design includes diverse power and communications, fire compartments, drainage, structural loading, environmental control, emergency access, and safe evacuation.",
    ],
    "3.9": [
        "Wet-pipe sprinklers contain water continuously; dry-pipe systems admit water after pressure release; preaction systems require a detection event before filling pipes. Choose arrangements with qualified fire specialists based on hazards, response time and accidental-discharge risk.",
        "A UPS bridges short interruptions and supports orderly shutdown; a generator supplies longer-duration power but needs start time, fuel and maintenance. Test the complete transfer path under realistic load, including cooling and network equipment.",
        "Physical controls work as a system: deterrents discourage, barriers delay, sensors detect, assessment confirms, and guards or responders intervene. Delay should be long enough for response to arrive.",
        "Access controls include badges, biometrics, locks, turnstiles, mantraps, visitor management, escorts, and anti-passback. Life safety and emergency egress must never be defeated.",
        "Fire protection combines early detection, alarm, compartmentation, appropriate suppression, shutdown, evacuation, and recovery. Match the extinguishing agent to the fire class and occupied environment.",
        "Power and environmental protection use conditioning, UPS, generators, grounding, HVAC, leak detection, temperature and humidity monitoring, and preventive maintenance.",
        "CCTV needs suitable field of view, lighting, resolution, retention, time synchronization, monitoring, and privacy controls; a camera alone does not provide an effective response.",
    ],

    # Domain 4 — Communication and Network Security
    "4.1": [
        "ARP maps IPv4 addresses to local hardware addresses; DNS resolves names; DHCP supplies host configuration; ICMP carries control and error messages. These supporting protocols affect availability and traffic direction even when applications use encryption.",
        "NAT translates addresses and may obscure internal addressing, but does not replace explicit access policy. A DMZ separates public services from internal systems; permitted flows should be limited in both directions.",
        "Common service associations include SSH 22, DNS 53, HTTP 80, HTTPS 443, LDAP 389 and LDAPS 636. A port number suggests an expected service but does not prove which application or protocol is actually using it.",
        "Use layered models to reason about function and encapsulation. Physical moves signals; data link handles local frames; network routes packets; transport provides end-to-end delivery; upper layers support sessions, representation, and applications.",
        "Segmentation limits broadcast scope, trust, and attack movement. VLANs provide logical separation but require routing and policy enforcement; security zones should reflect sensitivity, function, and exposure.",
        "Zero trust removes implicit trust based on network location. Continuously evaluate subject, device, resource, context, and policy; grant least-privileged, per-session access; and monitor outcomes.",
        "Resilient designs eliminate single points of failure through diverse paths, redundant devices and services, dynamic routing, capacity planning, failover, and protection of control and management planes.",
        "A /24 IPv4 subnet leaves 8 host bits: 256 addresses, conventionally 254 usable host addresses. Routers connect subnets; switches forward local frames using MAC addresses. TCP adds ordered, reliable delivery; UDP does not guarantee either.",
    ],
    "4.2": [
        "A stateless filter evaluates packet fields independently; a stateful firewall tracks sessions; an application proxy terminates and inspects application exchanges. A WAF addresses web traffic but cannot correct every authorisation or business-logic flaw.",
        "In 802.1X, the supplicant requests access, the authenticator controls the port, and the authentication server validates credentials through EAP. Port-based admission complements segmentation and endpoint controls rather than proving a device is continuously safe.",
        "Harden network devices by changing defaults, disabling unused services and ports, patching, using secure management protocols, restricting administrative sources, enforcing strong authentication, backing up configurations, and logging centrally.",
        "Switch protections include VLAN control, port security, 802.1X, DHCP snooping, dynamic ARP inspection, spanning-tree protections, and shutdown of unused interfaces.",
        "Routers enforce paths and filtering; firewalls enforce policy between zones; proxies terminate and relay application traffic; IDS detects; IPS can block. Placement and traffic visibility determine value.",
        "Protect management, control, and data planes separately. Out-of-band management, authenticated routing, configuration change control, and time synchronization support trustworthy operation.",
        "Wireless security depends on strong enterprise authentication, modern encryption, controlled access points, RF monitoring, guest isolation, secure configuration, and detection of rogue or evil-twin devices.",
    ],
    "4.3": [
        "End-to-end encryption keeps content protected between communicating endpoints; link encryption protects each individual hop, with intermediate devices potentially seeing plaintext. Traffic metadata and compromised endpoints may remain exposed in either design.",
        "DNSSEC authenticates signed DNS data and detects alteration; it does not encrypt queries. TLS protects a connection after certificate validation; it does not establish that the remote application or all content it serves is trustworthy.",
        "A secure channel authenticates endpoints, negotiates approved algorithms, establishes fresh keys, protects confidentiality and integrity, prevents replay, and handles certificate and session failure safely.",
        "TLS protects application sessions; IPsec protects IP traffic in transport or tunnel mode; SSH protects interactive administration and tunneling. Select the protocol at the layer and scope required.",
        "Remote access needs managed endpoints, MFA, least privilege, appropriate split-tunneling policy, posture checks, logging, session limits, and rapid revocation. A VPN does not make an endpoint trustworthy.",
        "Email protections address different risks: transport encryption protects links, end-to-end encryption protects content, signatures protect origin and integrity, and SPF/DKIM/DMARC reduce domain spoofing.",
        "Voice, collaboration, and wireless channels need signaling and media protection, secure configuration, segmentation, abuse prevention, emergency-service support, and monitoring.",
    ],

    # Domain 5 — Identity and Access Management
    "5.1": [
        "An access request should be checked against the resource and requested action, not simply whether the user has logged in. Reading a record, editing it, exporting it and changing its permissions may require different entitlements.",
        "Prevent privilege creep by separating ordinary use from administration and granting elevation only when needed. Emergency access should be time-limited, monitored and reviewed, with recovery paths tested before an incident.",
        "Access control starts with subjects, objects, requested operations, and policy. Physical and logical controls should share lifecycle events so a role change or termination affects every access path.",
        "Apply least privilege and need to know using deny by default, explicit grants, time and context limits, privileged access management, and periodic review.",
        "Administrative controls define who may approve access; technical controls enforce it; physical controls restrict presence. Strong security requires the three to agree.",
        "Monitor failed and successful access, privilege use, sensitive actions, policy changes, and anomalous behavior. Protect and review the resulting audit trail.",
    ],
    "5.2": [
        "Authentication and account recovery need comparable protection. A strong login loses value if a help desk can reset its credentials after weak identity checks; notify users of recovery events and revoke compromised authenticators.",
        "Phishing-resistant authentication binds the proof to the legitimate service, as with appropriately implemented WebAuthn. Passwords and manually entered one-time codes can be relayed to a fraudulent site; MFA methods differ in what threats they resist.",
        "Identity proofing establishes that a real-world subject is who they claim to be; enrollment creates the digital identity; credential binding connects authenticators to it; authentication verifies later claims.",
        "Factors are something known, possessed, or inherent, plus contextual attributes such as location or behavior. Multiple authenticators from the same factor do not provide true multi-factor authentication.",
        "Passwords need sufficient length, screened weak or breached values, protected storage using salted adaptive hashes, secure reset, rate limiting, and resistance to phishing and credential stuffing.",
        "Biometrics are probabilistic. False acceptance and false rejection move in opposite directions as thresholds change; crossover error rate compares system accuracy. Templates require strong protection because traits cannot be reissued easily.",
        "Machine and service identities need ownership, unique credentials, rotation, vaulting, scoped permissions, noninteractive controls, and monitoring just as human identities do.",
    ],
    "5.3": [
        "An ID token communicates an authentication result to its intended client; an access token authorises resource access; a refresh token obtains replacement access tokens. Validate each token for its intended use and protect long-lived refresh credentials.",
        "Single sign-on lets a user access multiple services without repeated login; federation crosses independently managed identity domains. Local logout may leave other sessions active, so session revocation and deprovisioning must be coordinated.",
        "Federation allows one security domain to rely on identity assertions from another. The identity provider authenticates; the service provider or relying party consumes the assertion and makes the access decision.",
        "SAML commonly supports browser enterprise SSO using signed XML assertions. OAuth delegates authorization to an API; OpenID Connect adds an identity layer and ID token to OAuth 2.0.",
        "Trust depends on metadata, keys and certificates, redirect URI control, audience and issuer validation, token lifetime, replay protection, claim mapping, and rapid revocation or deprovisioning.",
        "Federation contracts and architecture must define assurance level, attribute accuracy, privacy, incident handling, availability, logging, and termination of the trust relationship.",
    ],
    "5.4": [
        "Static separation of duties prevents conflicting role assignments; dynamic separation prevents conflicting actions within a session or transaction. A requester may be allowed to review other requests but prohibited from approving their own.",
        "The policy decision point evaluates a request; the policy enforcement point applies the decision. Consistent policy, fresh attributes and secure communication between these components prevent bypass and stale authorisation.",
        "Discretionary access control lets owners grant access; mandatory access control enforces labels and clearances; role-based control assigns permissions through job roles; attribute-based control evaluates subject, object, action, and context attributes.",
        "Example: RBAC grants payroll clerks payroll permissions. ABAC can additionally require a managed device, working hours and a matching region. An ACL lists who can access one object; a capability describes objects and actions available to a subject.",
        "Authorization should be enforced at every access, on the server or trusted policy enforcement point. Do not rely on hidden user-interface elements or client-side checks.",
        "Role engineering must avoid excessive roles and accumulated privilege. Use business roles, constraints, separation of duties, ownership, review, and removal of unused entitlements.",
    ],
    "5.5": [
        "Orphaned accounts lack a current owner or business purpose; dormant accounts have not been used for a defined period. Investigate dependencies before removal, especially scheduled tasks and service accounts, while promptly disabling unnecessary interactive access.",
        "Provisioning automation propagates lifecycle events through connectors or standards such as SCIM. Reconciliation verifies the actual downstream state because a successful request at the identity platform does not guarantee every application processed it.",
        "Joiner, mover, and leaver processes begin from an authoritative source and approved role. Automate routine provisioning while retaining accountable approval for sensitive or exceptional access.",
        "Movers create the greatest privilege-creep risk. Recalculate required access, remove conflicting or obsolete entitlements, and apply separation-of-duties checks before granting the new role.",
        "Periodic certification asks owners and managers to confirm continued need. Reconcile directories, applications, cloud platforms, physical access, service accounts, and privileged vaults.",
        "Termination should disable access promptly, revoke sessions and tokens, recover assets, transfer ownership, preserve required records, and verify completion across downstream systems.",
    ],
    "5.6": [
        "In Kerberos, the user first obtains a ticket-granting ticket, then uses it to request a ticket for a specific service. The service ticket and authenticator support access without sending the user's password to each application.",
        "Directory lookup, authentication and authorisation are separate functions. LDAP exposes directory information; the directory may support several authentication methods, while the application still enforces what the authenticated identity can do.",
        "Authentication protocols must protect credentials in transit and at rest, resist replay and man-in-the-middle attacks, bind the response to the correct server and session, and produce useful audit records.",
        "Kerberos uses a trusted key distribution center. The authentication service issues a ticket-granting ticket; the ticket-granting service issues service tickets; timestamps require synchronized clocks.",
        "RADIUS is widely used for network access and combines authentication and authorization; TACACS+ separates AAA functions and protects more of the exchange, making it useful for device administration.",
        "Single sign-on reduces password burden and centralizes control but increases dependence on the identity provider. Protect it with MFA, resilient design, secure recovery, conditional access, and monitoring.",
    ],

    # Domain 6 — Security Assessment and Testing
    "6.1": [
        "Coverage describes which assets, requirements and attack paths were examined; depth describes how thoroughly they were tested. A clean report from a narrow scope should not be interpreted as assurance over untested systems.",
        "Rules of engagement define permitted targets, techniques, accounts, hours, contacts, data handling and stopping conditions. Third-party infrastructure may require its owner's separate authorisation even when the application owner approves the assessment.",
        "Start with purpose and scope: assurance, compliance, control validation, vulnerability discovery, or adversary simulation require different methods and evidence.",
        "Define systems, locations, rules of engagement, authorization, test data, timing, communication, stop conditions, evidence handling, independence, and reporting before testing begins.",
        "Use a risk-based schedule and retest after significant change or remediation. Combine automated coverage with human analysis and use multiple evidence sources for important conclusions.",
        "A strategy should connect requirements to controls, test procedures, expected results, sampling, responsible testers, and acceptance criteria so results are repeatable and defensible.",
    ],
    "6.2": [
        "Credentialed scanning can inspect installed software and local configuration that external scanning cannot see. External tests expose the attacker's view; internal tests reveal segmentation and post-compromise paths. Use both when the objectives require them.",
        "Synthetic transactions exercise a known workflow to detect failures; real-user monitoring observes actual experience. Interface testing checks how components handle malformed input, failed dependencies, authentication and unexpected sequencing.",
        "A vulnerability assessment finds and prioritizes weaknesses; a penetration test safely demonstrates exploitable paths and impact. Neither alone proves the absence of vulnerabilities.",
        "Black-box testing provides little prior knowledge, white-box provides detailed access and design information, and gray-box lies between. Greater knowledge usually improves coverage and efficiency.",
        "Testing can include documentation review, interviews, observation, configuration analysis, scanning, code analysis, social engineering, physical attempts, exploitation, and post-exploitation within scope.",
        "Validate scanner findings, protect production, minimize collected data, document exact evidence, communicate critical discoveries immediately, clean up test artifacts, and retest fixes.",
    ],
    "6.3": [
        "Use a denominator: 900 patched systems means little without knowing whether the estate contains 1,000 or 10,000 systems. Track coverage and asset criticality alongside completion percentages to avoid misleading averages.",
        "Leading indicators track conditions that may precede harm, such as overdue critical patches; lagging indicators describe realised outcomes, such as incidents. Both need consistent measurement periods and investigation of changes in collection methods.",
        "Collect data that answers a defined control or risk question. Examples include coverage, timeliness, failure rate, exception age, detection time, response time, recurrence, and exposure duration.",
        "Define each metric's owner, source, calculation, frequency, threshold, audience, and limitations. Normalize data and maintain time synchronization so trends and correlations are meaningful.",
        "KPIs show performance toward objectives; KRIs show changing exposure; control indicators show whether safeguards operate. A raw activity count is not useful unless it supports a decision.",
    ],
    "6.4": [
        "A finding should connect condition, criterion, cause and effect: what exists, what should exist, why the gap occurred and what it could cause. Attach enough evidence for the owner to reproduce the issue without exposing unnecessary sensitive information.",
        "Closure requires verification, not just an implementer's statement. Retest the original condition and likely bypasses, record remaining limitations, and obtain risk-owner approval if remediation is incomplete or an exception is accepted.",
        "Analyze context before severity: validate the finding, identify affected assets and business processes, consider exposure and exploitability, evaluate existing controls, and estimate likelihood and impact.",
        "Separate confirmed findings, false positives, accepted exceptions, and observations. Group related symptoms under root causes so remediation addresses the underlying weakness.",
        "A false positive flags a safe condition; a false negative misses a real problem. CVSS expresses technical severity, not complete business risk: exposure, exploitation, asset importance and existing safeguards change remediation priority.",
    ],
    "6.5": [
        "Sampling reduces audit effort but creates uncertainty. Define the population, period and selection method; include higher-risk items deliberately and distinguish targeted samples from statistically representative ones.",
        "Management owns remediation; the auditor evaluates and reports independently. An auditor who designed and operated the control may face a self-review conflict when later asked to assure its effectiveness.",
        "An audit compares criteria with evidence. Establish scope and criteria, preserve independence, plan sampling, collect sufficient reliable evidence, document findings, obtain management response, and follow remediation to closure.",
        "Evidence quality generally improves from inquiry to observation, inspection, reperformance, and direct external confirmation. Corroborate important claims rather than relying on interviews alone.",
        "SOC 1 concerns controls relevant to financial reporting; SOC 2 addresses trust services criteria. Type I assesses design at a date; Type II also assesses operation over a period. Check scope, exceptions and controls the customer must implement.",
        "Internal audit supports organizational oversight; external audit provides independent assurance to defined users. Neither transfers management's responsibility for effective controls.",
    ],

    # Domain 7 — Security Operations
    "7.1": [
        "Live acquisition preserves volatile state but changes the running system; shutting down may destroy memory evidence or trigger encryption barriers. Choose and document the method according to incident goals, system behaviour, safety and legal authority.",
        "Chain of custody records possession and transfer; a cryptographic hash detects changes in content. Neither alone proves how evidence was originally created, so preserve contextual logs, timestamps and collection notes as well.",
        "Prepare before an incident by defining authority, contacts, tools, evidence procedures, legal escalation, storage, and trained roles. The first responder should stabilize the scene and avoid unnecessary change.",
        "Collect volatile evidence before less volatile evidence when safe and relevant. Record system time, actions, tools, source, handler, transfer, storage, and hashes so another examiner can reproduce and defend the process.",
        "Create bit-for-bit forensic images using write protection and analyze copies. Hash verification demonstrates that evidence remained unchanged; chain of custody demonstrates accountable possession.",
        "Root-cause analysis distinguishes the initiating weakness and contributing conditions from symptoms. Findings should drive corrective action without compromising legal or disciplinary proceedings.",
    ],
    "7.2": [
        "An event is an observable occurrence; an alert signals a condition needing attention; an incident is an occurrence assessed as threatening or violating security. Correlation combines events, but an analyst or validated automation must still establish context.",
        "Log failures can hide behind quiet dashboards. Monitor agent health, collection delay, dropped events, clock drift and storage limits; restrict sensitive contents such as tokens and passwords from entering logs in the first place.",
        "A logging architecture identifies required events, fields, sources, timestamps, transport, normalization, correlation, storage, retention, access, and review responsibilities.",
        "Centralization improves correlation and protects evidence from loss with the source system. Restrict log administration, use immutable or integrity-protected storage where appropriate, and monitor collection gaps.",
        "Baselines make anomalies visible. Tune detections with threat intelligence, asset criticality, identity context, and observed false positives, then document response procedures for each alert.",
        "Monitoring covers endpoints, networks, applications, cloud control planes, identity systems, physical systems, and third-party services. Gaps should be risk-assessed rather than silently accepted.",
    ],
    "7.3": [
        "A configuration baseline describes approved state; change management authorises transitions between states. A drift report may reveal unauthorised change, a failed deployment or an approved change whose records were not updated.",
        "Infrastructure as code makes changes reviewable and repeatable, but a compromised template can spread a flaw widely. Protect repositories and pipelines, validate templates before deployment, and compare deployed state with the approved version.",
        "Configuration management identifies configuration items, approved baselines, relationships, versions, and owners. It maintains the known state on which patching, recovery, audit, and troubleshooting depend.",
        "Build hardened images from documented standards, test them, approve them, deploy consistently, and continuously compare actual state with the baseline to detect drift.",
        "A CMDB is useful only when discovery, reconciliation, change processes, and accountable ownership keep it accurate. Unknown and stale records create operational and security blind spots.",
    ],
    "7.4": [
        "Dual control requires two people to complete an action; split knowledge prevents one person from knowing an entire secret. For key ceremonies, both may be used so no individual can reconstruct or use a protected key alone.",
        "Service accounts may require continuous access and cannot always follow human login rules. Assign an owner, restrict permitted hosts and actions, rotate credentials safely, monitor use and prohibit interactive login when unnecessary.",
        "Least privilege limits each identity to necessary actions; need to know limits access to necessary information; separation of duties divides conflicting tasks; dual control requires two participants for a sensitive action.",
        "Privileged operations should use separate named accounts, just-in-time elevation, credential vaulting, session recording, command logging, approval, and review. Shared administrator accounts weaken accountability.",
        "Service levels translate business expectations into measurable availability, capacity, response, recovery, and support commitments. Operational teams must monitor dependencies and escalate before thresholds are breached.",
        "Operational resilience combines trained people, documented procedures, capacity, redundancy, maintenance, monitoring, incident response, and recovery—not technology alone.",
    ],
    "7.5": [
        "With equal-size disks, RAID 5 typically provides (N−1) disks of capacity and tolerates one disk failure; RAID 6 provides (N−2) and tolerates two. RAID 10 can survive multiple failures only when they do not remove both members of a mirrored pair.",
        "Snapshots capture a point-in-time state but may depend on the original storage. Replication quickly copies changes, including corruption or deletion; independent protected backups are needed to recover from those failures.",
        "Backups protect recoverability only when scope, frequency, retention, isolation, encryption, integrity, and restoration are tested. Maintain multiple copies on different media with at least one offline or otherwise protected copy.",
        "After Sunday's full backup, restoring Wednesday's incremental chain needs Sunday plus Monday, Tuesday and Wednesday increments. A Wednesday differential restore needs Sunday plus Wednesday's differential. Missing an increment can break the chain.",
        "RAID improves availability but is not a backup. Mirroring duplicates data; parity arrays calculate recovery information; rebuild time, simultaneous failure, controller failure, corruption, and ransomware remain concerns.",
        "Protect media according to the data it contains throughout transport, storage, reuse, and disposal. Track custody and validate sanitization or destruction.",
        "Recovery design should remove shared failure domains across power, network, storage, identity, administration, geography, and software versions.",
    ],
    "7.6": [
        "Triage establishes what happened, what is affected, whether activity continues, and which business services are at risk. Severity drives escalation and resource allocation; preserve uncertainty explicitly rather than delaying all action until every fact is known.",
        "Incident response spans ongoing governance and preparation as well as detection, response and recovery. Traditional phase names remain useful operationally, but feedback and improvement occur throughout, not only at the final review.",
        "Preparation establishes policy, roles, tools, logging, playbooks, communications, evidence handling, external contacts, and exercises. Identification validates whether an event is an incident and sets severity.",
        "Containment limits harm while preserving essential evidence and business operations. Short-term isolation may precede a durable containment approach; eradication removes the cause after the spread is controlled.",
        "Recovery restores from a trusted state, validates security and function, increases monitoring, and returns service in stages. Closing too early risks reinfection or hidden persistence.",
        "Lessons learned capture timeline, impact, decisions, control gaps, costs, and assigned improvements. Update risk assessments, architecture, detections, playbooks, and training.",
    ],
    "7.7": [
        "EDR collects endpoint behaviour and supports investigation and containment; a SIEM correlates events across sources; SOAR orchestrates approved response workflows. Automation needs scope limits, audit records and a way to handle false positives.",
        "An allowlist permits approved applications or actions; a blocklist denies known unwanted ones. Allowlisting reduces unknown execution but requires a reliable approval and update process to avoid preventing legitimate work.",
        "Signature detection is precise for known patterns but misses novel variants; anomaly detection can find new behavior but needs baselines and tuning. Layer endpoint, network, identity, application, and data telemetry.",
        "A virus attaches to a host; a worm spreads independently; a Trojan masquerades as useful software; a rootkit hides privileged activity; a logic bomb triggers on a condition. Ransomware encrypts or steals data; these categories can overlap.",
        "Honeypots and deception assets generate high-signal observations but require isolation, monitoring, legal review, and clear objectives so attackers cannot use them against production.",
        "Test control health: sensor placement, agent status, content updates, bypasses, encrypted traffic visibility, alert delivery, case creation, and responder action.",
    ],
    "7.8": [
        "A vulnerability is a weakness; an exploit uses it; a patch changes software to remove or reduce the weakness. A zero-day may have no available patch, so immediate response can require isolation or disabling the affected feature.",
        "Patch success should be verified on the asset, including required restarts and version state. A deployment tool reporting delivery does not establish that the vulnerable component stopped running or that every replica was updated.",
        "Maintain an accurate inventory and vulnerability sources, scan with appropriate credentials, validate results, and prioritize using severity, exploitability, exposure, asset criticality, threat activity, and compensating controls.",
        "Test patches for security, function, performance, compatibility, and rollback. Deploy by risk-based rings, monitor failures, verify final state, and record exceptions.",
        "When patching is delayed or impossible, reduce exposure through segmentation, access restriction, feature disablement, virtual patching, monitoring, isolation, or replacement planning.",
        "Measure time to remediate, exposure age, coverage, recurrence, unsupported assets, and exception expiry. A scan count alone does not show reduced risk.",
    ],
    "7.9": [
        "A rollback plan specifies the previous version, backups, decision point, time limit and authority to reverse the change. Database schema or data transformations may make rollback difficult, requiring tested restoration or a planned forward correction.",
        "Standard changes are preauthorised and repeatable; normal changes receive risk-based review; emergency changes use an accelerated route. Each still needs traceability and validation proportionate to its potential impact.",
        "A change record describes purpose, scope, affected services, risk and impact, dependencies, implementation steps, testing, schedule, communications, approvals, rollback, and success criteria.",
        "Segregate request, approval, implementation, and validation for sensitive changes. Update configuration records, documentation, monitoring, recovery material, and training as part of completion.",
        "Emergency change paths accelerate review but do not eliminate authorization, testing where feasible, logging, rollback, or retrospective review.",
        "Post-implementation review checks intended results, unexpected effects, incidents, documentation, and lessons. Failed or unauthorized changes should feed process improvement.",
    ],
    "7.10": [
        "Active-active sites both process work and need adequate remaining capacity after failure; active-passive designs reserve a standby. Synchronous replication reduces acknowledged data loss but adds latency; asynchronous replication accepts a lag window.",
        "Validate that recovery capacity is actually reserved and accessible during a regional incident. Shared-site subscriptions, cloud quotas, scarce hardware and unavailable staff can prevent an otherwise sound recovery design from meeting its objectives.",
        "Select recovery strategies from BIA targets and dependency analysis. Compare activation time, capacity, data currency, geographic risk, staffing, security, testability, duration, and total cost.",
        "Hot sites provide ready infrastructure and rapid recovery; warm sites require some configuration or restoration; cold sites provide basic space and utilities. Labels are less important than proven ability to meet RTO and RPO.",
        "Reciprocal agreements may fail during a shared disaster or capacity conflict. Contracts need priority, resources, security responsibilities, testing, duration, and termination provisions.",
        "Cloud recovery still needs identity, network, keys, data, images, quotas, dependencies, and practiced orchestration in the target environment.",
    ],
    "7.11": [
        "Disaster declaration should use pre-agreed impact and duration thresholds, with named authority and alternates. Record the decision and communicate service priorities so technical teams do not restore systems in conflicting orders.",
        "Recovery validation must include data reconciliation and business acceptance. Successful booting or a passing health check is insufficient if transactions are missing, permissions are wrong or dependent suppliers cannot reconnect.",
        "A DR plan defines declaration authority, notification, team roles, safety, damage assessment, activation, communications, restoration priorities, dependencies, validation, return to normal, and plan maintenance.",
        "Recovery order comes from the BIA and technical dependencies. Restore shared services such as facilities, power, network, identity, DNS, keys, storage, and monitoring before dependent applications.",
        "Use clean, verified systems and data; validate security and business function before release. Record deviations, decisions, evidence, and outstanding risk during recovery.",
        "Reconstitution returns operations to a stable primary or replacement environment without losing changes made during contingency operation. Plan synchronization and fallback carefully.",
    ],
    "7.12": [
        "Measure actual recovery time from the defined starting event through business validation; measure achieved data recovery against the required RPO. Document assumptions such as preloaded data or available staff that made the test easier than a real event.",
        "Exercises need abort criteria and a safe restoration path. Protect production data and customer services, record deviations, and assign each discovered gap to an owner with a deadline and a follow-up test.",
        "Reviews and tabletop exercises validate documentation and decisions with little operational risk. Simulations add realistic inputs; parallel tests operate recovery capability alongside production; full interruption transfers live work and carries the greatest risk.",
        "Define objectives, scenario, scope, assumptions, success criteria, observers, safety controls, and communications. Test people and suppliers as well as technology.",
        "After the exercise, record actual timings, gaps, dependencies, decisions, and owners. Update plans, architecture, contracts, training, and risk records, then retest material corrections.",
    ],
    "7.13": [
        "Manual workarounds need capacity, authorisation and reconciliation rules. Paper transaction capture can keep a service operating, but later entry must prevent duplicated, lost or unauthorised transactions.",
        "Crisis communication identifies who may speak, which stakeholders need updates, what is known and when the next update will occur. Maintain alternate channels because email, telephony or the primary identity service may be unavailable.",
        "Continuity keeps critical products and services operating at acceptable levels while disaster recovery restores technology. Crisis management provides executive coordination and stakeholder communication.",
        "Strategies may include alternate processes, remote work, manual workarounds, cross-trained staff, alternate suppliers, stockpiles, geographic distribution, and technology recovery.",
        "Plans need activation criteria, authority, contact methods, succession, dependencies, procedures, communications, and return-to-normal steps. Store copies where they remain available during disruption.",
        "Exercises should cover plausible severe scenarios and absent leaders, failed communications, supplier outages, and extended duration—not only a single system failure.",
    ],
    "7.14": [
        "Tailgating bypasses individual authentication by following an authorised entrant. Combine staff behaviour, appropriate entry design and monitoring; anti-passback can detect inconsistent badge use but does not physically stop someone following another person.",
        "Keys and badges are credentials: issue to named holders, limit areas and times, inventory spares, revoke lost items and review contractor access. Master keys and access-system administrator accounts need especially tight custody.",
        "Operate physical controls through maintenance, testing, monitoring, staffing, and response. Broken sensors, propped doors, stale access lists, and unreviewed video undermine good designs.",
        "Manage visitors from preregistration through identity verification, badging, escort, area restriction, activity logging, and badge return. Delivery and maintenance access need equivalent control.",
        "Review physical access after role changes and termination, investigate anomalies, protect access-system records, and reconcile keys, cards, locks, and privileged areas.",
        "Coordinate security with facilities and safety for fire systems, environmental alarms, generators, fuel, water, HVAC, emergency access, drills, and regulatory inspection.",
    ],
    "7.15": [
        "Emergency plans must support visitors, contractors and people who need assistance, including accessible evacuation and designated helpers. Account for people at assembly points and report missing persons to trained responders.",
        "Remote and travelling staff need secure communication, emergency contacts, device-loss reporting and destination-specific preparation. Establish check-in and escalation arrangements proportionate to the assignment and local conditions.",
        "Life safety has priority over property, evidence, and service availability. Emergency controls must support evacuation, accessibility, accountability, medical response, and communication.",
        "Prepare for fire, severe weather, utility failure, civil disturbance, workplace violence, travel risk, and hazardous conditions according to site and workforce context.",
        "Use duress procedures, two-person rules where appropriate, check-in methods, trained wardens, assembly points, and alternate communication. Protect the privacy of personnel status information.",
    ],

    # Domain 8 — Software Development Security
    "8.1": [
        "Verification asks whether the implementation meets specifications; validation asks whether the delivered system meets its intended need. Security acceptance should cover both, including misuse cases and operational constraints.",
        "The V-model pairs development stages with corresponding test levels; spiral development revisits risks through successive cycles. Agile security work belongs in the backlog and acceptance criteria, with unresolved risk owned rather than silently deferred.",
        "Embed security in each lifecycle phase: governance and training; risk and requirements; threat modeling and architecture; secure implementation; verification; controlled release; monitoring and maintenance; and secure disposal.",
        "Security requirements should be specific, testable, traceable, prioritized, and linked to misuse cases, data classification, privacy, compliance, and acceptance criteria.",
        "Waterfall emphasizes sequential gates; iterative and agile methods deliver increments; DevOps automates delivery. Each can be secure when risk activities and evidence are integrated into its workflow.",
        "Production release needs approved artifacts, separation of environments and duties, signed or verified builds, configuration and secret control, change authorization, rollback, and monitoring.",
        "Maintenance includes vulnerability intake, dependency monitoring, patching, incident response, regression testing, and eventual retirement with data and credential removal.",
    ],
    "8.2": [
        "A signed build proves an artifact was signed by a particular key and has not changed; it does not prove its source was benign. Protect build inputs, build execution, signing keys and approval so provenance supports meaningful trust.",
        "Secrets include tokens, database credentials, signing keys and cloud access keys. Inject them through controlled secret stores, restrict lifetime and scope, avoid exposure in logs, and rotate them after suspected compromise.",
        "Protect repositories with strong identity, least privilege, branch protection, review, signed commits where appropriate, audit logs, backup, and prevention of secrets entering source history.",
        "Secure CI/CD pipelines because they can alter every release. Isolate runners, pin and verify dependencies, protect tokens, restrict deployment rights, scan artifacts, sign outputs, and retain provenance.",
        "Separate development, test, staging, and production accounts, data, credentials, and networks. Use representative synthetic or masked data rather than unrestricted production data.",
        "Manage infrastructure and container images as code through approved modules, hardened bases, policy validation, vulnerability scanning, immutable artifacts, and drift detection.",
    ],
    "8.3": [
        "Code coverage measures executed code, not absence of vulnerabilities. Tests must include negative cases: unauthorised objects, missing fields, boundary values, duplicate requests, unexpected sequence and failed downstream services.",
        "A test stub substitutes for a called component in top-down integration; a driver invokes a component in bottom-up integration. Both isolate behaviour but may hide defects in real interfaces, so complete integration tests remain necessary.",
        "Use complementary methods. SAST analyzes code without running it; DAST tests a running application; IAST observes the application during tests; SCA identifies vulnerable or disallowed dependencies.",
        "Manual review finds design, authorization, workflow, and context flaws that automated tools often miss. Risk-based review should focus on trust boundaries, sensitive operations, parsers, authentication, cryptography, and error handling.",
        "Fuzzing supplies malformed or unexpected input; unit tests verify components; integration tests verify interfaces; regression tests prevent old defects returning; abuse-case tests exercise hostile behavior.",
        "Triage findings for validity, reachability, exploitability, business impact, and existing controls. Fix root causes, add regression tests, and verify remediation in the deployed configuration.",
    ],
    "8.4": [
        "Source escrow requires defined release conditions, current deposited code, build instructions and necessary dependencies. Possessing source alone may not allow the customer to build, legally use or support a failed supplier's product.",
        "For SaaS, evaluate tenant isolation, data export, administrator roles, audit access and deletion arrangements. Product purchase shifts some operational work to the provider but still requires customer configuration and ongoing assurance.",
        "Evaluate acquired software before commitment: architecture, data use, authentication, logging, encryption, secure development, testing evidence, vulnerabilities, dependencies, deployment model, support, and supplier stability.",
        "Contracts should address security requirements, vulnerability notification, patch timelines, incident cooperation, data rights, audit evidence, subcontractors, availability, escrow where justified, end of support, and exit.",
        "Maintain an inventory of products, versions, components, licenses, owners, data flows, and support dates. Monitor advisories and supplier changes throughout operation.",
        "Open source is not inherently more or less secure. Assess maintenance activity, provenance, dependency health, known vulnerabilities, license obligations, and the organization's ability to support or replace it.",
    ],
    "8.5": [
        "SQL parameterisation binds user values separately from query structure; dynamic identifiers such as table names require controlled selection. Stored procedures remain vulnerable if they assemble unsafe dynamic SQL internally.",
        "XSS runs injected script in a victim's browser; context-appropriate output encoding and safe rendering reduce it. CSRF tricks a browser into sending an authenticated request; anti-CSRF tokens, appropriate cookie settings and origin checks address that different mechanism.",
        "A primary key uniquely identifies a row; a foreign key links it to another table and supports referential integrity. Normalisation reduces redundancy and update anomalies; denormalisation can improve performance but needs controls to keep duplicate representations consistent.",
        "Validate input against an allowlist of expected type, length, range, format, and business rules on a trusted system. Encode output for its destination context and use parameterized interfaces to separate data from commands.",
        "Enforce authentication and authorization on the server for every sensitive request and object. Use secure session identifiers, rotation, timeout, revocation, CSRF protection, and safe credential recovery.",
        "Handle errors safely: deny on failure, release resources, preserve transaction integrity, log useful internal detail, and return minimal information to users. Do not expose stack traces, secrets, or queries.",
        "Protect memory and concurrency through safe languages or libraries, bounds checks, initialization, lifetime management, atomic operations, locking discipline, resource limits, and testing under abnormal conditions.",
        "Database ACID: atomicity makes a transaction all-or-nothing; consistency preserves defined constraints; isolation controls concurrent interference; durability preserves committed results. Aggregation combines low-sensitivity data into sensitive knowledge; inference deduces hidden facts from permitted results.",
        "Manage dependencies and secrets explicitly. Pin and verify packages, monitor vulnerabilities, remove unused components, rotate exposed credentials, and never embed production secrets in code or images.",
    ],
}
